// SPDX-License-Identifier: Apache-2.0

// Builds the DTCG sources in tokens/ with Style Dictionary into dist/:
//   css/tokens.css     CSS custom properties, light default, dark redefined
//   json/tokens.json   the resolved flat token set
//   motion/motion.json durations (ms, frames24, frames60) and easings
// Run: `npm run build`. The output directory can be given as the first
// argument (check:fresh builds into a temp dir).
import { mkdirSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';
import { sourceFiles } from './validate-tokens.mjs';

const roles = ['bg', 'card', 'fg', 'muted', 'rule', 'accent-fill', 'accent-text', 'on-accent'];

const num = (n) => String(n).replace(/^(-?)0\./, '$1.');

/** Renders a resolved token value as a CSS value. */
export function cssValue(token) {
  const v = token.$value;
  switch (token.$type) {
    case 'cubicBezier':
      return `cubic-bezier(${v.map(num).join(',')})`;
    case 'fontFamily':
      return v.map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(', ');
    default:
      return String(v);
  }
}

/** Maps a token path to its CSS custom property name, or null if not emitted. */
export function cssName(path) {
  const [a, b, c] = path;
  if (a === 'color') {
    if (b === 'primitive') return `--color-primitive-${c}`;
    if (b === 'theme') return `--color-${path[3]}`;
    return `--color-${b}`;
  }
  if (a === 'motion' && b === 'duration') return `--duration-${c}`;
  if (a === 'motion' && b === 'easing') return `--ease-${c.replace(/^ease-/, '')}`;
  if (a === 'motion' && b === 'press') return `--press-${c}`;
  return `--${path.join('-')}`;
}

const header = '/* SPDX-License-Identifier: Apache-2.0 */\n/* Generated by `npm run build` from tokens/*.json. Do not edit. */\n';

function cssFormat({ dictionary }) {
  const light = [];
  const dark = [];
  const rest = [];
  for (const t of dictionary.allTokens) {
    const line = `${cssName(t.path)}: ${cssValue(t)};`;
    if (t.path[0] === 'color' && t.path[1] === 'theme') {
      if (t.path[2] === 'light') light.push(line);
      else if (t.path[2] === 'dark') dark.push(line);
    } else rest.push(line);
  }
  const block = (indent, lines) => lines.map((l) => `${indent}${l}`).join('\n');
  const darkLines = [...dark, 'color-scheme: dark;'];
  return `${header}
:root {
${block('  ', [...rest, ...light])}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${block('    ', darkLines)}
  }
}

:root[data-theme="dark"] {
${block('  ', darkLines)}
}
`;
}

function jsonFormat({ dictionary }) {
  const out = {};
  for (const t of dictionary.allTokens) {
    const e = { $value: t.$value, $type: t.$type };
    if (t.$description) e.$description = t.$description;
    if (t.$extensions) e.$extensions = t.$extensions;
    out[t.path.join('.')] = e;
  }
  return `${JSON.stringify(out, null, 2)}\n`;
}

function motionFormat({ dictionary }) {
  const out = { durations: {}, easings: {}, pressScale: null };
  for (const t of dictionary.allTokens) {
    const [a, b, c] = t.path;
    if (a !== 'motion') continue;
    if (b === 'duration') {
      const f = t.$extensions['com.cubealgos.frames'];
      out.durations[c] = { ms: Number.parseInt(t.$value, 10), frames24: f.fps24, frames60: f.fps60 };
      const w = t.$extensions['com.cubealgos.wipe'];
      if (w) out.durations[c] = { ...out.durations[c], inMs: w.inMs, outMs: w.outMs };
    } else if (b === 'easing') {
      const [x1, y1, x2, y2] = t.$value;
      out.easings[c] = { css: cssValue(t), x1, y1, x2, y2 };
    } else if (b === 'press') out.pressScale = t.$value;
  }
  return `${JSON.stringify(out, null, 2)}\n`;
}

/** Builds all outputs into [outDir] (cleared first). */
export async function build(outDir = 'dist') {
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });
  const sd = new StyleDictionary({
    usesDtcg: true,
    log: { verbosity: 'silent' },
    source: sourceFiles.map((f) => `tokens/${f}.json`),
    platforms: {
      css: { transforms: [], buildPath: `${outDir}/css/`, files: [{ destination: 'tokens.css', format: 'cubealgos/css' }] },
      json: { transforms: [], buildPath: `${outDir}/json/`, files: [{ destination: 'tokens.json', format: 'cubealgos/json' }] },
      motion: { transforms: [], buildPath: `${outDir}/motion/`, files: [{ destination: 'motion.json', format: 'cubealgos/motion' }] },
    },
  });
  sd.registerFormat({ name: 'cubealgos/css', format: cssFormat });
  sd.registerFormat({ name: 'cubealgos/json', format: jsonFormat });
  sd.registerFormat({ name: 'cubealgos/motion', format: motionFormat });
  await sd.buildAllPlatforms();
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const out = process.argv[2] ?? 'dist';
  await build(out);
  console.log(`build: wrote ${out}/css/tokens.css, ${out}/json/tokens.json, ${out}/motion/motion.json`);
}
