// SPDX-License-Identifier: Apache-2.0

// WCAG 2.2 contrast maths and the declared-pair evaluation behind
// `npm run check:contrast` (see contrast-check.mjs).

export const themes = ['light', 'dark'];
export const thresholds = { text: 4.5, 'large-text': 3, boundary: 3, decoration: null };
export const tolerance = 0.1;

/** Relative luminance of a `#RRGGBB` colour (WCAG 2.2). */
export function luminance(hex) {
  const m = /^#([0-9a-f]{6})$/i.exec(hex);
  if (!m) throw new Error(`not a #RRGGBB colour: ${hex}`);
  const [r, g, b] = [0, 2, 4].map((i) => {
    const c = Number.parseInt(m[1].slice(i, i + 2), 16) / 255;
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/** Contrast ratio of two colours, 1 to 21. */
export function ratio(a, b) {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}

const upper = (s) => s.toUpperCase();

/** Resolves a role name or full token path to a `{ path, hex }` for a theme. */
function resolve(tokens, name, theme) {
  const path = name.includes('.') ? name : `color.theme.${theme}.${name}`;
  const t = tokens[path] ?? tokens[`color.${name}`];
  if (!t) throw new Error(`unknown colour "${name}" (looked for ${path})`);
  return { path: tokens[path] ? path : `color.${name}`, hex: upper(t.$value) };
}

/**
 * Evaluates the declared pairs in both themes against the flat resolved
 * [tokens] (dist/json/tokens.json). Returns `{ rows, published }`; every row
 * has `pass` true, false, or null for a decoration exemption. A text or
 * boundary pair whose foreground is the accent-fill colour on a paper
 * background fails regardless of the ratio (the amber rule).
 */
export function evaluate(tokens, def) {
  const paper = upper(tokens['color.primitive.paper'].$value);
  const lightCard = upper(tokens['color.theme.light.card'].$value);
  const amber = upper(tokens['color.primitive.amber'].$value);
  const rows = [];
  for (const pair of def.pairs) {
    for (const theme of themes) {
      const kind = typeof pair.kind === 'string' ? pair.kind : pair.kind[theme];
      if (!(kind in thresholds)) throw new Error(`unknown kind "${kind}" for ${pair.fg}/${pair.bg}`);
      const fg = resolve(tokens, pair.fg, theme);
      const bg = resolve(tokens, pair.bg, theme);
      const r = ratio(fg.hex, bg.hex);
      const required = thresholds[kind];
      let pass = required === null ? null : r >= required;
      let reason = '';
      const onPaper = bg.hex === paper || bg.hex === lightCard;
      if ((kind === 'text' || kind === 'large-text' || kind === 'boundary') && fg.hex === amber && onPaper) {
        pass = false;
        reason = 'amber rule: amber is never text or a boundary on paper';
      }
      rows.push({ pair: `${pair.fg}/${pair.bg}`, theme, kind, ratio: r, required, pass, fg: fg.hex, bg: bg.hex, reason });
    }
  }
  const published = (def.published ?? []).map((p) => {
    const r = ratio(resolve(tokens, p.fg, 'light').hex, resolve(tokens, p.bg, 'light').hex);
    return { ...p, measured: r, pass: Math.abs(r - p.ratio) <= tolerance };
  });
  return { rows, published };
}

const fmt = (n) => n.toFixed(2);
const status = (r) => (r.pass === null ? 'exempt' : r.pass ? 'pass' : 'FAIL');

/** Plain-text table for the terminal. */
export function renderText({ rows, published }) {
  const head = ['pair', 'theme', 'kind', 'ratio', 'required', 'result'];
  const body = rows.map((r) => [
    r.pair, r.theme, r.kind, `${fmt(r.ratio)}:1`, r.required === null ? '-' : `${r.required}:1`,
    status(r) + (r.reason ? ` (${r.reason})` : ''),
  ]);
  const widths = head.map((h, i) => Math.max(h.length, ...body.map((b) => b[i].length)));
  const line = (cells) => cells.map((c, i) => c.padEnd(widths[i])).join('  ');
  const out = [line(head), line(widths.map((w) => '-'.repeat(w))), ...body.map(line), '', 'Published ratios (decision 10), tolerance 0.1:'];
  for (const p of published) {
    out.push(`  ${p.fg} on ${p.bg}: ${fmt(p.measured)}:1, published ${p.ratio}:1, ${p.pass ? 'pass' : 'FAIL'}`);
  }
  return `${out.join('\n')}\n`;
}

/** Markdown for docs/contrast.md. */
export function renderMarkdown({ rows, published }) {
  const out = [
    '<!-- Generated by `npm run check:contrast`. Do not edit. -->',
    '',
    '# Contrast',
    '',
    'WCAG 2.2 AA contrast of the declared role pairs (`tokens/contrast-pairs.json`) in both themes.',
    'Text needs 4.5:1, large text (at least 24 px, or 18.66 px bold) and UI boundaries need 3:1,',
    'decoration has no threshold and is listed so the exemption stays visible.',
    '',
    '| Pair (fg/bg) | Theme | Kind | Foreground | Background | Ratio | Required | Result |',
    '| --- | --- | --- | --- | --- | --- | --- | --- |',
    ...rows.map((r) => `| \`${r.pair}\` | ${r.theme} | ${r.kind} | \`${r.fg}\` | \`${r.bg}\` | ${fmt(r.ratio)}:1 | ${r.required === null ? 'n/a' : `${r.required}:1`} | ${status(r)}${r.reason ? ` (${r.reason})` : ''} |`),
    '',
    '## Published ratios',
    '',
    'Decision 10 published these; the check reproduces them within 0.1.',
    '',
    '| Foreground | Background | Measured | Published | Result |',
    '| --- | --- | --- | --- | --- |',
    ...published.map((p) => `| \`${p.fg}\` | \`${p.bg}\` | ${fmt(p.measured)}:1 | ${p.ratio}:1 | ${p.pass ? 'pass' : 'FAIL'} |`),
    '',
  ];
  return out.join('\n');
}

/** True when nothing failed. */
export const allPass = ({ rows, published }) => rows.every((r) => r.pass !== false) && published.every((p) => p.pass);
